# Generated by Django 3.1.6 on 2021-02-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.PositiveIntegerField(help_text='Enter phone number without country code')),
                ('house_name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('ration_card', models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL')], max_length=10)),
                ('annual_income', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, help_text='Max 100 letters', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.member')),
                ('requirement', models.ManyToManyField(to='charity.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.member')),
            ],
        ),
    ]
