# Generated by Django 3.1.6 on 2021-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemember',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
