# Generated by Django 3.1.6 on 2021-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='house_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='phone',
            field=models.CharField(help_text='Enter phone number without country code', max_length=10),
        ),
    ]
