# Generated by Django 3.1.6 on 2021-02-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20210217_0701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMember',
            new_name='Member',
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.member')),
            ],
        ),
    ]
