# Generated by Django 3.1.6 on 2021-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20210218_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement',
            field=models.ManyToManyField(blank=True, to='charity.Category', verbose_name='Requirement'),
        ),
    ]
