# Generated by Django 3.1.6 on 2021-02-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20210219_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charity.member'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('name', 'house_name', 'phone')},
        ),
    ]
