# Generated by Django 3.1.6 on 2021-02-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20210219_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Need',
        ),
    ]
